### ISSUE TITLE
Using Boats throws error in console

### ISSUE THREAD

**Issue by IR0NSIGHT** [Edgeburn/Horse-Highway#13]
occured in Beta-6 
I assume its new in Beta-6 because i didnt notice these errors in beta-5, but i might have just missed it :)

also thanks for fixing the dirtpath issue so fast <3

Being inside a boat (with and without chest) throws error:
[16:02:55 ERROR] [Minecraft] Could not pass event PlayerMoveEvent to HorseHighway vbeta-6

i also tried Llamas and minecarts, they didnt seem to cause errors.

the type of error thrown did also change at least once when using boats, and i cant remeber or recreate the first encountered one

full stacktrace:
```bash
[15:52:09] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to HorseHighway vbeta-6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:681) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.network.protocol.game.PacketPlayInVehicleMove.a(SourceFile:41) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.network.protocol.game.PacketPlayInVehicleMove.a(SourceFile:7) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.br(SourceFile:115) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1109) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R3.entity.CraftChestBoat cannot be cast to class org.bukkit.entity.Horse (org.bukkit.craftbukkit.v1_19_R3.entity.CraftChestBoat and org.bukkit.entity.Horse are in unnamed module of loader java.net.URLClassLoader @2e5d6d97)
	at com.edgeburnmedia.horsehighway.HorseHighwayListeners.onPlayerMove(HorseHighwayListeners.java:51) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 20 more
	```

**Comment by Edgeburn** [comment]
This should be fixed in beta 7, which is now available on Spigot and in the releases on this GitHub repo
